name: 'Dependency Review'
on: 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout Repository'
        uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@94145f3150bfabdc97540cbd5f7e926306ea7744
